//
// Created by wyskw on 25.01.2025.
//

#ifndef SIMULATIONPARAMS_H
#define SIMULATIONPARAMS_H

#define NUMBER_OF_POINTS 100
#define NUMBER_OF_GROUPS 5

#define NUMBER_OF_MULTIVARIATE_GAUSSIAN_DISTRIBUTION 5

#define MEAN_MAX 100
#define MEAN_MIN (-100)

#define POPULATION_SIZE 500
#define CROSSING_CHANCE 0.9
#define MUTATION_CHANCE 0.05

#define ITERATIONS 500

#endif //SIMULATIONPARAMS_H
